name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        preset: [debug, release, asan, ubsan]
        compiler:
          - { cc: gcc, cxx: g++ }
          - { cc: clang, cxx: clang++ }
    env:
      CC: ${{ matrix.compiler.cc }}
      CXX: ${{ matrix.compiler.cxx }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"

      - name: update apt
        run: sudo apt update

      - name: install deps
        run: sudo apt install ninja-build clang

      - name: configure
        run: cmake --preset ${{ matrix.preset }}

      - name: build
        run: cmake --build --preset ${{ matrix.preset }}

      - name: test
        run: ctest --preset ${{ matrix.preset }} --output-on-failure --verbose
